name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  emoji_picker_flutter: ^1.6.2
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: 
  video_player: ^2.7.2
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  flutter_contacts: ^1.1.7+1
  cupertino_icons: ^1.0.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/groups_white_36dp.svg
    - assets/person_black_36dp.svg
    - assets/background.png
    - assets/community.jpg    
    - assets/community.svg
    - assets/whatsAppIcon.svg
    - assets/Wicon.jpg
    - assets/video_call.png
