// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUgS7vn18g1GDMcX_EZ0aD7kzX72_jtps',
    appId: '1:631055442280:web:383a438dd59995ff1cf6dd',
    messagingSenderId: '631055442280',
    projectId: 'whats-app-clone-112b5',
    authDomain: 'whats-app-clone-112b5.firebaseapp.com',
    storageBucket: 'whats-app-clone-112b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7ONVgnCf8DN_q-HVbhXDSXvpU4V_tzM',
    appId: '1:631055442280:android:1864ece80b4a44901cf6dd',
    messagingSenderId: '631055442280',
    projectId: 'whats-app-clone-112b5',
    storageBucket: 'whats-app-clone-112b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKmjxpeledtmEOwLURl-aLQRhSEb2D3fQ',
    appId: '1:631055442280:ios:d266941f82b21a441cf6dd',
    messagingSenderId: '631055442280',
    projectId: 'whats-app-clone-112b5',
    storageBucket: 'whats-app-clone-112b5.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKmjxpeledtmEOwLURl-aLQRhSEb2D3fQ',
    appId: '1:631055442280:ios:3e748792b2eacec41cf6dd',
    messagingSenderId: '631055442280',
    projectId: 'whats-app-clone-112b5',
    storageBucket: 'whats-app-clone-112b5.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
